# Generated by Django 3.2 on 2023-12-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
